services:
  api-gateway:
    build: 
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - USER_SERVICE_URL=http://user-management-api:8080
      - SESSION_SERVICE_URL=http://session-management-api:8080
    depends_on:
      - redis
      - user-management-api
      - session-management-api

  session-management-api:
    build:
      context: ./SessionManagement.API
      dockerfile: Dockerfile
    ports:
      - "5110:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=SessionManagementDB;Username=postgres;Password=iulian
    depends_on:
      - postgres

  user-management-api:
    build:
      context: ./UserManagement.API
      dockerfile: Dockerfile
    ports:
      - "5170:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=UserManagementDB
    depends_on:
      - mongodb

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iulian
      - POSTGRES_DB=SessionManagementDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  redis-data:
  postgres-data:
  mongodb-data: